### ISSUE TITLE
Update Wes Hart Title

### ISSUE THREAD

**Issue by renkesn** [UNLV-FIA/UNLV-FIA-Group#126]
This existing employee profile needs to be updated with the information below.

Employee Name: Westly Hart

### Information to Update:
- Job Description: Update title to: Database Architect / System Administrator
- Improvement Goals List: Remove this line as Wes does not have improvement goals

![image](https://user-images.githubusercontent.com/65931068/215220505-c3aac8b5-09b3-42de-9a03-b20f53a917f1.png)

### Important Notes:
- Ensure the new employee is added alphabetically to the list (leave Brenda & Gretchen as the first two no matter what)
- Ensure newly added images are similar in size (200x200) or that they are cropped/expanded evenly to fit size requirements
- Ensure newly added divs, buttons, dialogs, etc. are given unique IDs (if an ID was necessary for that element)
- Ensure your updated employee profile hasn't disrupted the functionality/information of any existing employee

**Comment by Kelvyn-Meyers** [comment]
Hi @renkesn,

Wes' profile has been updated by Michelle and is ready for QA. She had to use a shortened version of the job title that appears beneath his image because its significantly longer than all of the other job titles and ends up messing up the visuals of the page. However, the full job title appears when you expand his profile dialog. If you would prefer something different there, let us know!
