### ISSUE TITLE
4.1.2 Name, Role, Value (A)

### ISSUE THREAD

**Issue by Kelvyn-Meyers** [UNLV-FIA/UNLV-FIA-Group#67]
### 4.1.2 Name, Role, Value - Level A
For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.

_Note 1: This success criterion is primarily for Web authors who develop or script their own user interface components. For example, standard HTML controls already meet this success criterion when used according to specification._

[Understanding 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html)
[How to Meet 4.1.2](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=131%2C133%2C141%2C143%2C211%2C212%2C221%2C231%2C242%2C245%2C246%2C247%2C312%2C322%2C411%2C412#name-role-value)
[How to Test 4.1.2, 2.D](https://usfs.box.com/s/r5r5hhlh6cgqs3bo06booiezklaz5kjm)
[How to Test 4.1.2, 5.E](https://usfs.box.com/s/ef9cpv0aqlnmwovhql9sim7pri5hsscw)
[How to Test 4.1.2, 6.B](https://usfs.box.com/s/kba7gsnp0e4vt20c2aw6tevimlh199ku)
[How to Test 4.1.2, 12.C-D](https://usfs.box.com/s/ar0ms8d8i3lwnzsnq2hjbjqrnr2wxuxu)

**Trusted Tester IDs:**
- [x] Test 2.D change-notify-auto
- [x] Test 5.E change-notify-form
- [x] Test 6.B change-notify-links
- [x] Test 12.C frame-title
- [x] Test 12.D iframe-name

**Accessibility Principle:** Robust (Compatible)

**Comment by AlanaBayless** [comment]
Overall, all three pages pass 4.1.2 Name, Role, Value:

- [ ] Test 2.D change-notify-auto: DNA, the content on the pages does not update or change automatically.
- [ ]  Test 5.E change-notify-form: DNA, there aren’t any form elements on any of the pages, therefore, the content on the pages does not change due to form interaction.
- [ ]  Test 6.B change-notify-links: PASS, when the profile buttons are activated on the Teams page focus shifts to the dialogue box, this provides sufficient description of the change in content.
- [ ]  Test 12.C frame-title: DNA, No Frames are identified using ANDI on any of the pages.
- [ ]  Test 12.D iframe-name: DNA, ANDI does not identify iframes on any of the pages.
